### ISSUE TITLE
Crashing/Freezing when loading playlist images

### ISSUE THREAD

**Issue by MeapVR** [austinried/subtracks#106]
See title.

https://meap.gg/dl/clips/Subtracks_Playlist_Bug.mp4

**Comment by austinried** [comment]
@MeapVR If you want to test the fix for this, you can install the development version from here: https://github.com/austinried/subtracks/actions/runs/2199995589

The download is at the bottom under Artifacts, unzip that file and then you can install the APK.  You'll need to uninstall the release version if you try this one since it's signed with the development key.
