### ISSUE TITLE
Allow Self-Signed Certificates

### ISSUE THREAD

**Issue by NGC602** [austinried/subtracks#17]
Currently there is no available option to "Skip Server Certificate Validation" or to "Allow Self Signed Certificates"

Without this it does not seem possible to connect this to a self hosted server for use on VPN/LAN only. 

If possible, please include this feature in a later build to allow self hosted internal Subsonic media servers to work with this application

**Comment by austinried** [comment]
Good catch, I overlooked this since my personal server doesn't use a self-signed cert and the demo servers I've been using are public http.  It seems like there was a change in Android security awhile back that changed how this works, I've found some info here so far: https://github.com/facebook/react-native/issues/20488#issuecomment-409535369

I'll keep looking into this and see if I can get it working.

**Comment by mradermaxlol** [comment]
Has there been any progress on this lately?

**Comment by austinried** [comment]
@mradermaxlol Yep, took me a bit to get a proper test setup for this but I've got a fix now that I can confirm works with a manually installed CA cert and self-signed certificates created with that CA.  Will be out in the next release.

**Comment by RobertZenz** [comment]
Excuse me hijacking this issue, but I think my issue is pretty much the same. I have a server sitting in my local LAN which does have a Let's Encrypt certificate for a (public) domain, however, given that I'm sitting right next to it (literally) I want to access it through my local network. When I'm using the IP address, Subtracks immediately returns with "Network error" when pressing "Test Connection". When using the DNS name for the local network, the "Test Connection" and "Save" buttons just get disabled, the dialog just sits there for a few minutes, and then shows the "Network error" message.

So most likely the certificate gets rejected (why it does take that long when using the name, I don't know), and given that the name in the certificate does not match, importing it will do nothing (as far as I'm aware).

I would have expected it to ask whether it is okay to accept the certificate, or is that simply an unsupported use-case?

**Comment by austinried** [comment]
Yes that would be unsupported, I don't think implementing a separate trust store for certificates is in scope for this application.  In your case I would either look into setting up a custom route in your router to redirect requests from inside the network to your public domain back into your home network IP instead of the public IP (I do this with the public domain to my own VPN at home actually to avoid routing issues), or set up a separate reverse proxy with no HTTPS/a different valid certificate for the internal domain name.

**Comment by RobertZenz** [comment]
> Yes that would be unsupported, I don't think implementing a separate trust store for certificates is in scope for this application.

It wouldn't need to be trust-store at all, a checkbox allowing to disable certificate verification (making it a NOOP) would be quite sufficient. FairEmail for example does it like that.
