### ISSUE TITLE
No sound, no playback notification with ALAC file

### ISSUE THREAD

**Issue by infinitejones** [austinried/subtracks#2]
Subtracks on my Pixel 5 authenticates with my Navidrome instance and downloads all artists/albums/tracks etc (including artwork), but no there's audio when playing individual tracks.

Screenshot of playing track attached - progress indicator progresses as expected, but no audio either from phone speaker or via Bluetooth headset. (I note the icon at the bottom left stays greyed out while the track is playing - not sure if that's relevant)

About Phone screenshot attached too, FWIW

Exactly the same tracks play just fine on Music Stash (another Subsonic API client) on the same phone, same Navidrome instance, same wi-fi network, same bluetooth headset etc

![Screenshot_20210831-170006](https://user-images.githubusercontent.com/5801868/131462705-1797fd1a-fa1f-44b0-927b-5cbb714f72e1.png)
![about phone](https://user-images.githubusercontent.com/5801868/131462721-471aec8c-98a4-4db2-b9e3-3b2684e13f25.png)

**Comment by austinried** [comment]
Thanks for creating the issue here, I'm going to see if I can reproduce this in a simulator on my end. Can you give me any more info on the source you're playing as well? What server you're using, what format the songs are in (mp3, flac, etc), and if the server is transcoding?

**Comment by infinitejones** [comment]
It's an ALAC (Apple Lossless) file - if you want to test with the file from my screenshot, download it here: 

https://drive.google.com/file/d/1GVV8Ec5UTPvh5k-cTZPixEmE93lARFQf/view?usp=sharing

I've just tested with an MP3 and that does play as expected.

Transcoding is not activated, so Navidrome is serving the ALAC.

**Comment by austinried** [comment]
Interesting, I can reproduce the issue here with that file (no sound, progress bar moves as normal) and I'm also not able to play that file from the Navidrome web player either.  I can play it in VLC at least though so I can see that it's working somewhere.

ALAC isn't a format I can say I'm familiar with, but I did some research and it sounds like it doesn't have great support in many players.  Here's a similar issue in Navidrome I found: https://github.com/navidrome/navidrome/issues/813#issuecomment-796808522

I'm using `react-native-track-player` to handle audio playback/streaming, which on Android uses ExoPlayer on the backend to actually play audio, which in turn mostly relies on the platform version of Android itself for its playback codecs, and [ALAC isn't one of them](https://developer.android.com/guide/topics/media/media-formats#audio-formats).  However, it seems like I might be able to add ALAC support by building ExoPlayer with the [ffmpeg extension](https://exoplayer.dev/supported-formats.html#ffmpeg-extension) to enable support for it.

So it looks like this is less of a bug and more of a lack of codec support from Android/ExoPlayer.  Frustratingly it doesn't seem to even throw me an error that I can use to notify you when you're playing a track with (this specific) unsupported format.  I'll look into getting ExoPlayer built with that extension next and see if I can get support for ALAC added, while also seeing if I can improve the error messaging situation here at all.

**Comment by austinried** [comment]
In the meantime, while probably not ideal, you should also be able to get this to work by enabling a transcoding profile for subtracks in your Navidrome settings.

**Comment by infinitejones** [comment]
Thanks, I'll just activate transcoding to MP3.

Good point about ALACs (not) playing in the Web UI in Chrome - I don't recall having problems with it in the past, but that issue indicates it exists, and today I definitely can't play ALACs in Chrome. Maybe I've had transcoding activated previously without realising it.

But, just as a final point about ALAC - the substreamer Android app can play them. I've attached a screenshot of the contents of the "Players" list in the main web UI when I was testing this (always with the same track, the one I supplied above).

It plays on my Pixel 5 with substreamer, but doesn't with Subtracks. Nothing else has changed in between the two attempts.

![navidrome players](https://user-images.githubusercontent.com/5801868/131759716-26d9a8fb-c1ed-4a0b-b1c7-364b4ac0a933.png)

**Comment by austinried** [comment]
I'm guessing substreamer is either using a different library for audio playback on Android or they are also using ExoPlayer but building it with that ffmpeg extension. Unfortunately since it isn't open source I can't look to see.

Either way though it doesn't look too tough to enable for me, I'm planning on working on it once I finish getting the F-Droid build up and working.

**Comment by ghenry22** [comment]
@austinried substreamer is just using the standard Android system media player:
android.media.MediaPlayer

So it will support whatever the device supports on it's given version of Android.  I've looked into exo player before but ended up just using the system media player as it does everything I need for now.

If exoplayer can be compiled with ffmpeg to extend it's codec support to anything that ffmpeg supports then that becomes a pretty interesting option to think about.

**Comment by austinried** [comment]
If you want to try a development build (you'll need to uninstall your release version first) with ALAC playback enabled you can grab the APK from here: https://github.com/austinried/subtracks/suites/3707940419/artifacts/90567550

**Comment by infinitejones** [comment]
That's working on my Pixel 5, using the track that definitely wouldn't play
in the first place. Screenshot shows no transcoding is happening for the
Subtracks player, so it's definitely playing the ALAC file.

Loving your work - thanks!

[image: image.png]
