### ISSUE TITLE
Artist Artwork

### ISSUE THREAD

**Issue by gonjat** [austinried/subtracks#25]
Any plans to have the artist artwork display in app? This is one flaw that I seemed to have with any *onic server. If your app could grab it from an external source, I could jump ship from Jellyfin. Until then I will remain on Jellyfin. Great looking app and fantastic work so far though!

**Comment by austinried** [comment]
Artist artwork does display currently, but with all subsonic servers it is dependent on the server to fetch and deliver the art as specified in the API.  Usually this means you'll need to do some extra setup though since they pull them from external sources that require a login or token.  Navidrome for example pulls from Spotify: https://www.navidrome.org/docs/usage/external-integrations/#spotify

**Comment by cn4750** [comment]
Perhaps a fallback solution could be to use one of the album art for the artist as a placeholder instead of the gray/white star like how other players like Poweramp do it.
