### ISSUE TITLE
[Feature] Translation Support

### ISSUE THREAD

**Issue by ghost** [austinried/subtracks#30]
Add support for translations via strings.xml and translation services (e.g., [weblate](https://weblate.org))

**Comment by comradekingu** [comment]
I think GPLv3+ (or later) Instead of GPLv3- (only) makes for fewer problems because going "only" is then always possible.
https://hosted.weblate.org/projects/subtracks/#information

Can be changed in
https://hosted.weblate.org/settings/subtracks/subtracks/
https://hosted.weblate.org/settings/subtracks/glossary/

**Comment by austinried** [comment]
I think I'll keep it at GPLv3-only for now to match the project.  If v4 comes out and it seems better I can change them both at that time.

**Comment by austinried** [comment]
Also thanks for adding the Norwegian translation @comradekingu! I locked the project for a little bit because I'm still building out the strings but I've unlocked it again for now as I think they're mostly stable.  I'm going to try to get that branch merged in soon and then add an announcement to the readme.
