### ISSUE TITLE
Pauses when switching between Wi-Fi & mobile data

### ISSUE THREAD

**Issue by dror3go** [austinried/subtracks#54]
When switching network connection from mobile data to Wi-Fi or vice versa - the playback pauses and resumes after a few seconds.
Ideally the player should keep playing and seamlessly continue streaming.

**Comment by kusky3** [comment]
it might also depend on the bitrate you've chosen for wifi and mobile data.
if it's different than it has to stop because the server has to transcode

**Comment by austinried** [comment]
This is probably not something I will be able to fix with my current streaming strategy.  I have to rebuild the queue with new playback URLs that have that new bitrate whenever it changes, and getting ExoPlayer to keep playback going on the old file until the buffer runs out would involve some deep messing with react-native-track-player which is handling that queue.

Ideally when offline playback is implemented though this should get better, since it will be caching entire tracks and can rely more on those caches for playback.
