### ISSUE TITLE
[Feature Request] "Songs" tab for library

### ISSUE THREAD

**Issue by krisu5** [austinried/subtracks#92]
Basically way to list all the songs from the server.

**Comment by austinried** [comment]
This one's a little tough because the subsonic API doesn't expose a way to actually list all songs.  There are three methods that would mostly to do the job though:

http://www.subsonic.org/pages/api.jsp#getSongsByGenre
http://www.subsonic.org/pages/api.jsp#getRandomSongs
http://www.subsonic.org/pages/api.jsp#getStarred2

I had planned to implement these as some of the lists you could choose to display on your home tab (with the ability to open the list and view more than what you see on the home screen currently), but I guess it also makes sense to implement them in the library tab.  The only issue is going to be that there would be no "all" or "by name/by artist" sort, but I think that would be alright

**Comment by krisu5** [comment]
> This one's a little tough because the subsonic API doesn't expose a way to actually list all songs. There are three methods that would mostly to do the job though:

Tbh, I suspected such, because none of the apps I have used also don't have this feature. Weird that API doesn't support this.

I guess random songs or song by genre would be fine, even if not ideal.

**Comment by krisu5** [comment]
Well, I guess workaround for Navidrome users is smart playlists: https://github.com/navidrome/navidrome/issues/1417

At least with this, you could use Subsonic app with playlists feature to get similar results.

**Comment by emes81** [comment]
One great thing about a songs tab would be that it presumably would also make it possible to shuffle all songs from the whole library.

Or, given that you note the http://www.subsonic.org/pages/api.jsp#getRandomSongs method in Subsonic, would there be another way of implementing that?

**Comment by rightsaidfred99** [comment]
Installed symfonium from the play store and it seems they have a song tab from navidrome. Using it I could see every song on my server. I suppose there is a workaround or something. Wish I knew more about coding lol

**Comment by krisu5** [comment]
[Symfonium](https://play.google.com/store/apps/details?id=app.symfonik.music.player) seems nice, but it currently doesn't let add my Navidrome server.

The workaround is prorably something we already mentioned here. Austinried could ask more detail [in their forum](https://support.symfonium.app/).

App isn't open source unfortunately.

**Comment by deluan** [comment]
Navidrome dev here. What Symfonium does is "synchronize" everything from the server locally, calling `/search3` endpoint, passing "" as query and paginating 500 items each time:
```
http://navidrome/rest/search3.view?query=%22%22&songOffset=0&songCount=500&albumOffset=0&albumCount=0&artistOffset=0&artistCount=0
http://navidrome/rest/search3.view?query=%22%22&songOffset=500&songCount=500&albumOffset=0&albumCount=0&artistOffset=0&artistCount=0
http://navidrome/rest/search3.view?query=%22%22&songOffset=1000&songCount=500&albumOffset=0&albumCount=0&artistOffset=0&artistCount=0
...
```

It does the same for artists and albums. This way when you are browsing your library it uses the local copy of it, not the Subsonic endpoints. Not sure how it deals with outdated/stale data though...

**Comment by austinried** [comment]
Hmm, not sure I like that design to be honest.  Having to deal with possible cache invalidation of each song/album/artist seems very tricky to handle and probably not a great user experience when something goes missing.  How does it handle cases where a song/album/artist is available locally but missing on the server, or how do you get it to pick up new additions to the library? Full refresh/resync?

At the moment I'm already going to be handling caching of a lot of this data, but in a user-controlled manner for offline support, so in that case it doesn't really matter if it's not available on the server anymore since we can still play the song from the local copy.

**Comment by hedgepigdaniel** [comment]
> calling /search3 endpoint, passing "" as query and paginating 500 items each time

It looks like in the current `main`, Subtracks 2.0 now does more or less this (in `_syncAllSongs`). In my case (Navidrome, 15,000 songs), it takes 8 seconds. The great thing is you can perform all browsing/search functions even if the internet is not working.

**Comment by austinried** [comment]
It does now actually, yeah. I started the flutter rewrite with the same "online-first" strategy I was using before, but I wasn't happy with how I would have to handle downloads in a database of cached offline info anyway, and after remembering @deluan's suggestion here I switched to the "offline-first" strategy and I think I'm much happier with it.

So now a songs tab is already in the first alpha, and displaying/playing it is pretty much the same as showing any other song list.

**Comment by pyluyten** [comment]
a comment mentions http://www.subsonic.org/pages/api.jsp#getStarred2

Very interesting, because i believe subtracks currently lacks "favorite songs" tab. We have favorite albums/artists/playlist. Not favorite songs -> as soon as i shoot a client on a computer i rush to this because i miss it on phone

So if easier than "all songs" it is worth considering - i hope so! 10 bucks and all my gratitude for someone adding this!

**Comment by austinried** [comment]
@pyluyten you can do this in the current alpha now actually! On the songs tab you have similar sort/filter options to the other tabs, and you can fitler them by starred. Your last used filters/sort options should also be saved so you don't have to change it all the time.

**Comment by austinried** [comment]
Actually since this is in the current alpha already I'm going to close this now.  Definitely still open to changes though so feel free to make another issue.
